info:
  name: "Produkt anlegen"
  type: http
  seq: 1

http:
  method: POST
  url: "{{baseUrl}}/products"
  body:
    type: json
    data: |-
      {
        "name": "Bruno-ETag-Birne",
        "price": 1.2
      }
  auth: inherit

runtime:
  scripts:
    - type: after-response
      code: |-
        bru.setVar("productId", res.getBody().id);
  assertions:
    - expression: res.status
      operator: eq
      value: "201"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
